# Generated by Django 2.0.dev20170623013156 on 2017-06-23 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Criar_mentoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Criar mentoria',
                'verbose_name_plural': 'Criar mentorias',
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mentoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_e_horario', models.DateTimeField()),
                ('mentor_email', models.CharField(editable=False, max_length=200)),
                ('mentorando', models.CharField(blank=True, editable=False, max_length=200)),
                ('status', models.CharField(choices=[('D', 'Disponível'), ('A', 'Agendada')], default='D', editable=False, max_length=1)),
                ('criar_mentoria', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Mentorias.Criar_mentoria')),
                ('disciplina', models.ManyToManyField(to='Mentorias.Disciplina')),
                ('mentor', models.ForeignKey(editable=False, limit_choices_to={'groups': 2}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
